source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

gem 'rails', '~> 6.1.4'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'jbuilder'
gem 'rails-i18n'
gem 'flipper'
gem 'flipper-active_record'

group :development, :test do
  gem 'pry', '~> 0.13.0'
  gem 'pry-byebug', '~> 3.9.0'
  gem 'psych', '3.3.2' # faker incompatibility with psych 4
  gem 'faker'
  gem 'rubocop', '~> 1.18', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'brakeman'
  gem 'rubycritic'
end

group :test do
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers'
  gem 'json_matchers'
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'webmock'
  gem 'simplecov', require: false
  gem 'fuubar'
end
